---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-wordpress
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-wordpress
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-ghost
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-ghost
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-gitea
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-gitea
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-node-api
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-node-api
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "256Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-flask-api
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-flask-api
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "256Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-react
  labels:
    project: cloud-forge
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: stack-react
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "256Mi"
    limits.cpu: "500m"
    limits.memory: "512Mi"
---
apiVersion: v1
kind: Namespace
metadata:
  name: stack-portal
  labels:
    project: cloud-forge
