server:
  persistentVolume:
    size: 8Gi
  retention: "15d"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: NodePort
    nodePort: 30090
  ingress:
    enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false
