server:
  persistentVolume:
    size: 8Gi
  retention: "15d"
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - ""
    path: /prometheus
    pathType: Prefix

alertmanager:
  enabled: false

pushgateway:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
