global:
  domain: argocd.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  ingress:
    enabled: false

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
