apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloud-forge
  source:
    repoURL: https://github.com/denfr18/cloud-forge
    targetRevision: claude/integrate-argocd-giiVs
    path: charts/flask-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stack-flask-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
