apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloud-forge
  source:
    repoURL: https://github.com/denfr18/cloud-forge
    targetRevision: main
    path: charts/gitea
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stack-gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
