apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: {{ .Values.image }}
          env:
            - name: url
              value: "http://{{ .Values.ingress.hostPrefix }}.{{ .Values.ingressHost }}"
            - name: database__client
              value: sqlite3
            - name: database__connection__filename
              value: /var/lib/ghost/content/data/ghost.db
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-storage
              mountPath: /var/lib/ghost/content
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ghost-storage
          persistentVolumeClaim:
            claimName: ghost-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
